- README.md
- make_ghpages/mod/templates/singlepage.html
Introduce the optional "external_url" key for `metadata.json` in app root folders.
External URL is an optional key, whose value should be a URL to the application's homepage.
For example, for the `aiidalab-aiida-tutorials` app the external URL may be:
```json
metadata.json:
{
"external_url": "http://www.aiida.net",
...
}
```
The documentation URL is now correctly retrieved for `singlepage.html`.
The link to the application's code homepage has been given a label prior to the link in `singlepage.html`.
> External URL

- make_ghpages/mod/templates/main_index.html
- make_ghpages/mod/templates/singlepage.html
+ add version to index
+ rename "app homepage" to "source code"
Rationale: Since the doc url is currently empty for every app, there is no point in boasting about this in our index.
Furthermore, I think it's perfectly fine to first click on the app to see quickly what it is about, and then from there go to a documentation.
> remove doc url from index

- .travis-data/deploy.sh
- .travis-data/run_script.sh
- .travis.yml
- make_ghpages/exceptions.py
- make_ghpages/make_pages.py
- make_ghpages/requirements.txt
- make_ghpages/test_make_pages.py
Checks that the URL created from the value of "logo" in an app's `metadata.json` can be reached/is valid.
Add `pytest` tests that are also run by Travis (currently testing this).
**Note**: The latter is perhaps not necessary, but also doesn't hurt. I have done it mainly to learn `pytest` and how to interact with Travis. Can always remove the tests but keep in the logo validation part.
> Validate logo URL and add pytests

- .travis-data/run_script.sh
./deploy.sh must be called from the directory where it is located.
All deploys since 8b99859a15e768f80024b07e7304f61140007661 have failed
due to this.
> try fixing run_script

- apps.json
The structure manager/importer app is not needed anymore,
as its functionalities have been moved to the aiidalab-
widgets-base app.
> Remove structure importer app.

- apps.json
The app was copying the user's home folder to the daint supercomputer. 
This is too specific and can't be generalized at the current state of things.
Moreover, the home drive of AiiDA lab users is backed up anyways.
> Remove backup app.

- apps.json
fixes #36 
The app has been merged with aiidalab-epfl-lsmo, see the PR:
https://github.com/lsmo-epfl/aiidalab-epfl-lsmo/pull/8
> Remove persistence homology app from the registry.

- apps.json
fixes #35 
The app is outdated and not maintained any longer.
> Remove the vasp-example app from the registry.

- README.md
- apps.json
~It is added with backwards-compatibility, i.e., it is OPTIONAL and if
not supplied the current default (`master`) will be used.~
UPDATE: Instead of adding a new key, this PR simply makes the list of current keys for the JSON files in the README look nicer and more transparent.
Also fixed some indentation issues in `apps.json`. No content has been
changed in `apps.json`.
~This is related to aiidalab/aiidalab#60~
> Prettify list of JSON keys in README

- apps.json
The old link points to a non-existing file.
> Fix the link to metadata.json file of OPTIMADE app.

- apps.json
~According to the "offline" determined system of how to report release sources, I have updated the `aiidalab-optimade` app's `git_url` value, specifying the branch to be used by default.~
Update: This PR will be changed to temporarily remove the `aiidalab-optimade` application. It will be reinstated once a repository re-factoring has happened.
> (Temporarily) remove aiidalab-optimade

- schemas/metadata.schema.json
This change to the schema adds the `requires` key that app developers can use to publish their app requirements as part of the app metadata.
> Add optional 'requires' key to app metadata.

- apps.json
Hi, we developed a simple app to run tight-binding mean-field Hubbard calculations and would like to add it to the registry.
> add empa tb-mfh app

- tests/test_validate_schemas.py
Instead of one test per schema. Removes the need to modify the test
whenever a schema is added or removed.
The next couple PRs are going to introduce various new schemas which makes the test maintenance more cumbersome than necessary.
> Test all available schemas within one test.

- .github/workflows/deploy.yml
To work-around the chicken and egg issue with publishing the schemas
as part of the deployment process.
> Mock schemas endpoints during build for deployment.

- apps.yaml
Point to CasperWA/voila-optimade-client after releasing version 2021.8.6 and the `develop` branch after @csadorf added all AiiDAlab-required files in PR CasperWA/voila-optimade-client#327.
As far as I understand, this should use version 2021.8.6 and forwards, correct?
> Update aiidalab-optimade pointers

- src/mod/templates/base.html
The word "AiiDAlab" linked to the MARVEL AiiDAlab instance instead of
the generic landing page explaining what the AiiDAlab is.
> fix link on app registry

- apps.yaml
This is blocked by https://github.com/aiidalab/aiidalab-qe/pull/232.
If I understand correctly @csadorf comment on https://github.com/aiidalab/aiidalab-registry/issues/88#issuecomment-1123738458 about multiple releases of an app, in this PR I remove the duplicate metadata between two previous release. Moreover, I add a concise one for newly released `v22.05.0`.
> Remove overlap and update qe-app info

- apps.yaml
fixes #112 
I think it is more proper to add the `external_url` to the metadata at the moment instead of moving to read metadata all from the app repository. We are not guaranteed that the metadata format of every app is correct, which will bring more work to us. So this change is more reliable.
> Adding external_url to the metadata for apps which are lacking this field

- apps.yaml
- requirements.txt
After https://github.com/aiidalab/aiidalab/pull/383 (merged and released), this change can be supported.
> fetch all tags for legacy support

- .github/workflows/deploy.yml
- README.md
This allowed the workflow can be triggered manually by developers with write permission https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
Sometimes we want to see the change and deployment of registry as soon as possible.
> Adding workflow dispatch so the deploy can be triggered manually

- apps.yaml
The `metadata` is no longer needed, aidialab will fetch the data from the `setup.cfg` file.
> remove metadata of aiida-archive-inspect

- .github/workflows/ci.yml
- .github/workflows/deploy.yml
- .pre-commit-config.yaml
- README.md
- requirements.txt
- setup.cfg
This update includes:
- https://github.com/aiidalab/aiidalab/pull/429
- aiidalab/aiidalab#451 which fixes #103 (tested locally  by running `./build.sh`)
Also includes basic repo cleanup:
- Remove unneeded pre-commit hooks
- trivial CI updates
- update links in README
> Update aiidalab package
